//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wSpecXY.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("client_credentials")]
        public string bidu_grant_type {
            get {
                return ((string)(this["bidu_grant_type"]));
            }
            set {
                this["bidu_grant_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dw6P5IePRc4kQXH6aVZfQXZj")]
        public string bidu_client_id {
            get {
                return ((string)(this["bidu_client_id"]));
            }
            set {
                this["bidu_client_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wucm4GXSvKhZpVFZOopfdxvFDNAfXmVq")]
        public string bidu_client_secret {
            get {
                return ((string)(this["bidu_client_secret"]));
            }
            set {
                this["bidu_client_secret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bidu_access_token {
            get {
                return ((string)(this["bidu_access_token"]));
            }
            set {
                this["bidu_access_token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string bidu_cuid {
            get {
                return ((string)(this["bidu_cuid"]));
            }
            set {
                this["bidu_cuid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zh")]
        public string bidu_lan {
            get {
                return ((string)(this["bidu_lan"]));
            }
            set {
                this["bidu_lan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("288F2S09NyBs")]
        public string ibot_app_key {
            get {
                return ((string)(this["ibot_app_key"]));
            }
            set {
                this["ibot_app_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jbF17nlMnzHN7UZH59Sw")]
        public string ibot_app_secret {
            get {
                return ((string)(this["ibot_app_secret"]));
            }
            set {
                this["ibot_app_secret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api-vxxnrhzs")]
        public string ibot_user_id {
            get {
                return ((string)(this["ibot_user_id"]));
            }
            set {
                this["ibot_user_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int syn_voice_id {
            get {
                return ((int)(this["syn_voice_id"]));
            }
            set {
                this["syn_voice_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int syn_voice_speed {
            get {
                return ((int)(this["syn_voice_speed"]));
            }
            set {
                this["syn_voice_speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cfg_recog {
            get {
                return ((int)(this["cfg_recog"]));
            }
            set {
                this["cfg_recog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cfg_intrp_ibot {
            get {
                return ((bool)(this["cfg_intrp_ibot"]));
            }
            set {
                this["cfg_intrp_ibot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cfg_wave_fmt {
            get {
                return ((int)(this["cfg_wave_fmt"]));
            }
            set {
                this["cfg_wave_fmt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cfg_intrp_simsimi {
            get {
                return ((bool)(this["cfg_intrp_simsimi"]));
            }
            set {
                this["cfg_intrp_simsimi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string local_serialize {
            get {
                return ((string)(this["local_serialize"]));
            }
            set {
                this["local_serialize"] = value;
            }
        }
    }
}
